# Generated by Django 4.0.4 on 2022-10-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_APP', '0001_initial'),
    ]

    operations = [
        
    ]
