# Generated by Django 4.0.4 on 2022-10-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_APP', '0002_remove_reservas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='hora_reserva',
            field=models.TimeField(),
        ),
    ]
